name: ci
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install X (Linux)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get update -y
        sudo apt-get install xorg-dev -y

    - name: Install Mingw64 (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        choco install make mingw

    - name: Build (Non-Windows)
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        make all BUILD_TYPE=Release -j4

    - name: Build (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        mingw32-make all BUILD_TYPE=Release -j4

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}
        if-no-files-found: error
        path: ./build/

  update-ci-release:
    needs: [build]
    permissions:
      contents: write
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: dev-drprasad/delete-tag-and-release@v0.2.1
      with:
        tag_name: latest-git
        delete_release: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/download-artifact@v3
      with:
        name: windows-latest
        path: ./windows-latest

    - uses: actions/download-artifact@v3
      with:
        name: ubuntu-latest
        path: ./linux-latest

    - uses: actions/download-artifact@v3
      with:
        name: macos-latest
        path: ./macos-latest

    - name: Rename
      run: |
        mv ./windows-latest/CachedRenderer.exe ./CachedRenderer-win.exe
        mv ./linux-latest/CachedRenderer ./CachedRenderer-linux
        mv ./macos-latest/CachedRenderer ./CachedRenderer-macos

    - uses: ncipollo/release-action@v1
      with:
        name: "CachedRenderer Nightly Build"
        body: "this release is not for daily use."
        tag: "nightly"
        commit: "master"
        prerelease: true
        allowUpdates: true
        generateReleaseNotes: true
        artifactErrorsFailBuild: true
        artifacts: |
          ./CachedRenderer-win.exe
          ./CachedRenderer-linux
          ./CachedRenderer-macos

